[package]
name = "min-manual"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <https://mayconfmelo.netlify.app>"]
license = "MIT-0"
description = "Simple and sober manuals inspired by the OG linux manpages"
categories = [ "layout", "utility" ]
keywords = [ "manual", "doc", "documentation" ]
repository = "https://github.com/mayconfmelo/min-manual"
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".gitignore",
  "justfile"
]

[template]
path = "template"
entrypoint = "manual.typ"
thumbnail = "/docs/assets/thumbnail.png"